#!/usr/bin/env perl

# git f(eature-branch)diff - show diff for a feature branch

use strict;
use warnings;

use Getopt::Long;

GetOptions(
  'full|p|patch' => \(my $full = 0),
  'reverse|r|tac' => \(my $reverse = 0),
);

my $args = join ' ', @ARGV;
$args ||= '';

if ($full) {
  my $reverse = $reverse ? ' | tac ' : '';
  system(qq!git fdiff $reverse | (while read b; do b=\$(echo \$b | cut -f 1  -d " "); git log -p \${b}; done)!);
} else {
  my $log = $args ? qq{log "$args"} : qq{log };
  system(qq{git $log --pretty=oneline \$(git merge-base origin/base HEAD)...HEAD});
}

