#!/usr/bin/env perl

# git f(eature-branch)diff - show diff for a feature branch

use strict;
use warnings;

use Getopt::Long;

GetOptions(
  'full|p|patch' => \(my $full = 0),
  'reverse|r|tac' => \(my $reverse = 0),
  'branch|b=s' => \(my $branch = 'HEAD'),
);

my $args = join ' ', @ARGV;
$args ||= '';

if ($full) {
  my $reverse = $reverse ? ' | perl -lne "unshift @o, \$_; END { print foreach @o }" ' : '';
  system(qq!git fdiff --branch $branch $reverse | (while read b; do b=\$(echo \$b | cut -f 1  -d " "); git log --stat=120,120 -p \${b}; done)!);
} else {
  my $log = $args ? qq{log "$args"} : qq{log };
  system(qq{git $log --pretty=oneline \$(git merge-base origin/master $branch)...$branch});
}

