#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;

GetOptions(
   'vmhost=s' => \(my $vmhost = 't1-dev'), # from your ~/.ssh/config
);

my ($command, @too_many) = @ARGV;
die "Don't know how to handle: $command @too_many\n" if @too_many;
die "Usage: $0 [up | down] \n" if ! $command;

# dispatch action or complain
(
  +{
    up => sub { _make('vagrant.up FLAVOUR=perl-dev') },
    down => sub { _make('vagrant.suspend FLAVOUR=perl-dev') },
  }->{$command} || sub { die "$command: don't know what you want me to do!\n" }
)->();

# wrap chdir-and-make-and-chdir-back
sub _make {
  my ($make_target) = @_;

  chomp(my $owd = `pwd`);

  my @candidates = (
    "$ENV{HOME}/code/platform-api-automation",
    "$ENV{HOME}/src/platform-api-automation",
  );
  my ($dir) = grep { -d $_ } @candidates; 

  if (! $dir) {
    my $pretty_dirs = join "\n", map { "\t$_" } @candidates;
    die "couldn't find platform-api-automation, looked under\n$pretty_dirs\n";
  }

  chdir $dir;
  system("make $make_target");
  chdir $owd;
}
