#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;
my_log("$^X @ARGV");
GetOptions(
	'newline!' => \(my $newline = 1),
	'version' => \(my $version),
	'root=s' => \(my $root = $ENV{code_root}),
);

my $short = $newline;

sub my_log {
	my ($string) = @_;
	open my $fh, '>>', "$ENV{HOME}/.whichpm-log";
	print $fh "$string\n";
	close $fh;
}

my $m = module_to_file(shift(@ARGV));
foreach my $dir (@INC) {
	if (-f "$dir/$m") {
		print "$dir/$m" . ($newline ? "\n" : "");
		last;
	}
}

sub module_to_file {
	my ($module) = @_;
	(my $filename = $module) =~ s{::}{/}g;
	return "$filename.pm";
}
