#!/usr/bin/env perl

my $args = join ' ', @ARGV;

my @find_opts = qx{/usr/bin/find --help | tr ' ' '\n' | sort | uniq | grep -P '^-(?!(?:N|-))'};
@find_opts = (<DATA>) if ! @find_opts;

foreach (@find_opts) {
  chomp;
	s{^-}{};
  $args =~ s{(?<!\b$_\b )\b($_)\b}{-$1}g;
}

my $run = $ENV{DEBUG}
  ? sub { exit warn "@_\n" }
  : sub { exec @_ };

# fix up args a little
$args =~ s{-type d -name git}{-type d -name .git};

$run->("/usr/bin/find", split ' ', $args);

__DATA__
type
name
prune
print
ignore
o
a
__END__

=pod

=head1 NAME

find - like find, but it'll put in all the dashes for you, yo

=head1 BUGS

any double-dash arguments won't get handled right

=head1 AUTHOR

Chet

=cut
