#!/bin/bash

scad::pushd () {
  pushd ${1} > /dev/null 2>&1
}

scad::popd () {
  popd > /dev/null 2>&1
}

# here's how you do a getopts in shell
verbose=1
opts=`getopt -o v -- "$@"`;
eval set -- "$opts";
while true; do
  case $1 in
    -v) verbose=0; shift ;;
    --) shift; break ;;
  esac
done

if [[ -z ${1} ]]; then
  echo "Usage: $0 [-v] filename"
  exit 1
fi

if stty | grep -q echo > /dev/null 2>&1; then
  stty echo
else
  [[ $verbose ]] || stty -echo
    if [[ ! -d ~/scad ]]; then
      mkdir -p ~/scad
      scad::pushd scad
        git init > /dev/null 2>&1
      scad::popd
    fi

    scad::pushd ~/scad
      cat >> ${1}
      git add ${1} > /dev/null 2>&1
      git commit -m "scad ${1} $(date +%s)" > /dev/null 2>&1
    scad::popd
  [[ $verbose ]] || stty echo
fi
